application: presentationmgr
version: 2
runtime: python27
api_version: 1
threadsafe: yes

handlers:

- url: /css
  static_dir: statics/css

- url: /admin.*
  script: presentations.app
  secure: always
- url: .*
  script: main.app



- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico



libraries:
- name: setuptools
  version: "latest"

- name: ssl
  version: "latest"

- name: jinja2
  version: "latest"

- name: webapp2
  version: "2.5.1"
