
application: presentationmgr
version: 9-beta
runtime: python27
api_version: 1
threadsafe: yes

handlers:

- url: /favicon\.ico
  static_files: static\presentation_icon.ico
  upload: favicon\.ico

- url: /static
  static_dir: static

- url: /js
  static_dir: static/js

- url: /css
  static_dir: static/css

- url: /img
  static_dir: static/img


- url: /_ah/upload.*
  script: main.app

- url: /.*
  script: main.app
  secure: always



libraries:
- name: setuptools
  version: "latest"

- name: ssl
  version: "latest"

- name: jinja2
  version: "latest"

- name: webapp2
  version: "2.5.1"


pagespeed:
  enabled_rewriters:
  - InlineCSS
  - InlineJs
  - CollapseWhitespace
